### ISSUE TITLE
Can not restore preferences

### ISSUE THREAD

**Issue by xi7i6** [captinc/Batchomatic#1]
I did backup my tweaks and preferences using online deb, but the tweak preferences may have not been backed up , i tried multiple times and still got the same results no preferences backed up.

**Comment by captinc** [comment]
Can you show me what’s inside /var/mobile/BatchInstall/Preferences?

**Comment by xi7i6** [comment]
[cid:9ACAA6EE-A649-4D00-A19B-262365A32E9E-L0-001]


Sent from my iPhone

On 11 Mar 2020, at 12:02 AM, captinc <notifications@github.com> wrote:

﻿

Can you show me what’s inside /var/mobile/BatchInstall/Preferences?

**Comment by captinc** [comment]
That’s.......not /var/mobile/BatchInstall/Preferences (if it exists). Can you try again please?

**Comment by xi7i6** [comment]
Yes it is

**Comment by captinc** [comment]
Hmmm thats super weird. Can you send me a screenshot of that folder?

**Comment by xi7i6** [comment]
Here u are

**Comment by captinc** [comment]
I think u forgot to attach a link/picture

**Comment by xi7i6** [comment]
What about nowSent from my iPhoneOn 11 Mar 2020, at 6:28 PM, captinc <notifications@github.com> wrote:﻿
I think u forgot to attach a link/picture

**Comment by captinc** [comment]
Still no

**Comment by xi7i6** [comment]
Can i have ur twitter or anything so i can send u the vid?

Sent from my iPhone

On 11 Mar 2020, at 8:04 PM, captinc <notifications@github.com> wrote:

﻿

Still no

**Comment by captinc** [comment]
Just upload to imgur.com and send the link here. But if u want my reddit: reddit.com/u/captinc37

**Comment by xi7i6** [comment]
https://imgur.com/gallery/SRIrUb4 Okay

Sent from my iPhone

On 12 Mar 2020, at 5:28 AM, captinc <notifications@github.com> wrote:

﻿

Just upload to imgur.com and send the link here. But if u want my reddit: reddit.com/u/captinc37

**Comment by captinc** [comment]
Everything looks normal. Now open up Cydia, go to the search tab, tap the steering wheel, tap “Install .deb”, enable “Install preferences”, and tap “Proceed”

**Comment by xi7i6** [comment]
I did that multiple times i could not get my preferences back , lt was fine before a few updates cant remember the version .

Sent from my iPhone

On 12 Mar 2020, at 2:27 PM, captinc <notifications@github.com> wrote:

﻿

Everything looks normal. Now open up Cydia, go to the search tab, tap the steering wheel, tap “Install .deb”, enable “Install preferences”, and tap “Proceed”

**Comment by captinc** [comment]
What is the size of /var/mobile/BatchInstall/Preferences?

If you still can’t get it work, you could manually copy everything in /var/mobile/BatchInstall/Preferences to /var/mobile/Library/Preferences (this will do the same thing as using Batchomatic normally)

**Comment by xi7i6** [comment]
Its size is 113.3 kb , thanks i will try to do it manually .

Sent from my iPhone

On 12 Mar 2020, at 9:52 PM, captinc <notifications@github.com> wrote:

﻿

What is the size of /var/mobile/BatchInstall/Preferences?

If you still can’t get it work, you could manually copy everything in /var/mobile/BatchInstall/Preferences to /var/mobile/Library/Preferences (this will do the same thing as using Batchomatic normally)

**Comment by xi7i6** [comment]
Sorry its 45.4 kb

Sent from my iPhone

On 12 Mar 2020, at 9:52 PM, captinc <notifications@github.com> wrote:

﻿

What is the size of /var/mobile/BatchInstall/Preferences?

If you still can’t get it work, you could manually copy everything in /var/mobile/BatchInstall/Preferences to /var/mobile/Library/Preferences (this will do the same thing as using Batchomatic normally)

**Comment by captinc** [comment]
That size is correct. Let me know if manual works

**Comment by xi7i6** [comment]
Yes it worked fine. Idk what causes that not to automatically be done by Batchomatic

Sent from my iPhone

On 12 Mar 2020, at 11:50 PM, captinc <notifications@github.com> wrote:

﻿

That size is correct. Let me know if manual works

**Comment by captinc** [comment]
Try deleting any .license file from /var/mobile/BatchInstall/Preferences and then re-run Batchomatic

**Comment by xi7i6** [comment]
I just bought a new iPhone X pro max and batchomatic did not work either

Sent from my iPhone

On 13 Mar 2020, at 3:02 PM, captinc <notifications@github.com> wrote:

﻿

Try deleting any .license file from /var/mobile/BatchInstall/Preferences and then re-run Batchomatic

**Comment by captinc** [comment]
Sounds like you have a slightly-messed-up Preferences folder or something

**Comment by xi7i6** [comment]
Idk, i will just do it manually for now, thank you for you help bro i love u☺️

Sent from my iPhone

On 13 Mar 2020, at 7:56 PM, captinc <notifications@github.com> wrote:

﻿

Sounds like you have a slightly-messed-up Preferences folder or something
