### ISSUE TITLE
Online deb files have the same size as the offline files

### ISSUE THREAD

**Issue by resso91** [captinc/Batchomatic#18]
Hi, thank you for the great tweak bro. I have been using the tweak for a long time however recently I was on ios 13.5 and wanted to update my phone to ios 14.3, and when I wanted to create an online deb the tweak created an offline one instead even though I chose the online option. I went with the huge file the tweak created and I updated successfully however the tweak still creates online deb files that are +2gb

![145D428F-AA7E-4F64-B587-0CC32DE11205](https://user-images.githubusercontent.com/84035753/117855000-91182e00-b279-11eb-8641-6f282191f0cb.png)

**Comment by captinc** [comment]
This is a general support question, so GitHub issues is not the appropriate place. It backs up everything in /var/mobile/BatchInstall/SavedDebs and everything in /var/mobile/Library/Preferences, so if the produced .deb is very large, then something in one of those 2 directories is also very large. Check those 2 directories for any large items, and if appropriate and safe to do so, delete them if you wish. Lastly, re-run the online .deb creator.
