### ISSUE TITLE
Does not show in Zebra

### ISSUE THREAD

**Issue by Healy1818** [captinc/Batchomatic#2]
I’m on latest version of Batchomatic and zebra. I have an iPX on 13.3.1 using latest checkra1n. 

Steering wheel does not show on Zebra search tab. It does show up in Cydia and in Installer. 

I have tried uninstalling and reinstalling batchomatic.

**Comment by captinc** [comment]
Batchomatic is not compatible with Zebra 1.1-beta yet. When Zebra 1.1 official is released, I will update Batchomatic to add support for it. 

This is because wstyres made several changes to Zebra in 1.1, so I need to wait for wstyres to finish his changes before I can add support for it

**Comment by Healy1818** [comment]
>Batchomatic is not compatible with Zebra 1.1-beta yet. When Zebra 1.1 official is released, I will update Batchomatic to add support for it.  ...

@captinc ok awesome! Thank you so much! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
