### ISSUE TITLE
Broken on zebra 

### ISSUE THREAD

**Issue by inline6power** [captinc/Batchomatic#3]
Anyway you could update this to work with the new and current zebra 3-3 beta 4? It worked fine when I was on 1.0.7 but once I updated zebra to the newest it does not work. Steering wheel does not show up

**Comment by captinc** [comment]
Here’s why it doesn’t work and when I will be able to fix it 

https://github.com/captinc/Batchomatic/issues/2

**Comment by inline6power** [comment]
Thanks
