### ISSUE TITLE
Unable to recover

### ISSUE THREAD

**Issue by DevynKitten** [captinc/Batchomatic#4]
Hello I’m have a certain issues sending my deb from my iPhone to my iPad I have it in the usual place to reinstall but get a error saying it’s no there. Anyone have a fix for this? IPad Pro 11in (a2013)
![E1FD67E6-0F55-493B-A5E8-88C23930E137](https://user-images.githubusercontent.com/21302988/80956479-ef891180-8dc6-11ea-97f5-8c567d554c17.png)

**Comment by captinc** [comment]
In Filza, you need to tap ON the .deb & tap “Install” at the top right corner. Not just move the .deb into that folder

**Comment by DevynKitten** [comment]
> In Filza, you need to tap ON the .deb & tap “Install” at the top right corner. Not just move the .deb into that folder

Thank you so much feel like this information should be placed on the front page Until internal installation is working.

**Comment by captinc** [comment]
FYI, what I told you is blatantly stated in the dialog that you posted a screenshot of. It’s ok though, I’m glad you got it working!
