### ISSUE TITLE
Hybrid Online/Offline Mode

### ISSUE THREAD

**Issue by samaero** [captinc/Batchomatic#5]
I’ve got some tweaks that I want to keep, but are no longer hosted on active repos. To avoid having to create an offline deb for everything, I think it’d make sense to have a “hybrid” mode that keeps offline copies of these tweaks while retaining online mode for everything that can still be found in the user’s repos. Happy to test if you decide to try to implement this!

**Comment by captinc** [comment]
Something similar to this kind of already exists

You can use the repack feature to make debs of the no-longer-hosted tweaks & then put them inside /var/mobile/BatchomaticDebs/UserSavedDebs. Now create an online deb like normal & everything inside UserSavedDebs will be included

When you install your .deb, turn on “Install saved .debs”

The only problem is the repack feature can only do one tweak at a time. But I will add a multi-repack feature in the upcoming update

**Comment by samaero** [comment]
Oh that's awesome. Thank you for the tip!
