### ISSUE TITLE
Can’t export to ‘any’ of the options 

### ISSUE THREAD

**Issue by Rhysdavies99** [captinc/Batchomatic#9]
I’m trying to export my online .debs and when I try to export to files, it gives a blank screen and the screen closes straight away

**Comment by captinc** [comment]
I’m pretty sure its another issue with the new unc0ver update. I will need update Batchomatic to support it soon

In the meantime, try typing this into terminal: “bmd online all”. It does the same thing as creating a deb in Cydia

**Comment by Rhysdavies99** [comment]
The command worked and I could see the .deb fill in Filza, but when I
transferred the file and folder into
/var/mobile/Library/Mobile Documents/com~apple~CloudDocs
The folder was there but no .deb file

**Comment by captinc** [comment]
Why not export directly to Files.app from inside Filza?

**Comment by captinc** [comment]
Will look into this further with the upcoming Zebra update
